import {
  db,
  Country,
  Images,
  Visa,
  VisaCountryExemptionList,
  VisaCountryRejectionList,
  VisaRequirement,
} from "astro:db";
import countryList from "./data/countries/index";
import { VisaAU } from "./data/countries/australia";

export default async function seed() {
  await db.insert(Country).values(countryList);

  await db.insert(Visa).values(VisaAU);

  await db.insert(VisaCountryExemptionList).values([
    {
      countryId: 12,
      visaId: 1,
      id: 1,
      name: "Argentina",
    },
    {
      countryId: 12,
      visaId: 3,
      id: 2,
      name: "Argentina",
    },
    {
      countryId: 12,
      visaId: 3,
      id: 3,
      name: "France",
    },
    {
      countryId: 12,
      visaId: 3,
      id: 4,
      name: "Germany",
    },
    {
      countryId: 12,
      visaId: 4,
      id: 5,
      name: "Argentina",
    },
  ]);

  await db.insert(VisaCountryRejectionList).values([
    {
      countryId: 12,
      visaId: 1,
      id: 1,
      name: "Albania",
    },
    {
      countryId: 12,
      visaId: 3,
      id: 2,
      name: "France",
    },
    {
      countryId: 12,
      visaId: 3,
      id: 3,
      name: "France",
    },
    {
      countryId: 12,
      visaId: 4,
      id: 4,
      name: "Germany",
    },
    {
      countryId: 12,
      visaId: 5,
      id: 5,
      name: "Albania",
    },
  ]);

  await db.insert(VisaRequirement).values([
    {
      countryId: 12,
      visaId: 1,
      id: 1,
      applicationFormName: "DS40",
      applicationFormCode: "DS40",
      applicationFormUrl: "DS40",
      appointmentConfirmationRequired: true,
      documentType: "DS40",
      documentValidity: "DS40",
      documentPhotocopyQuantity: "DS40",
      eligibilityAge: "DS40",
      eligibilityAgeRange: "DS40",
      eligibilityOccupation: "DS40",
      eligibilityFamilyMember: "DS40",
      feeLocalCurrency: "DS40",
      feeLocal: 500,
      feeUsd: 100,
      photoType: "DS40",
      photoSizeMm: "4x4 cm",
      photoSizeIn: "2x2 cm",
      photoBackgroundColor: "DS40",
      photoQuantity: 4,
      bankStatementRequired: true,
      bankStatementAmountLocal: 5000,
      bankStatementAmountUsd: 1000,
      bankStatementAmountMonths: 3,
      employmentProofRequired: true,
      healthInsuranceRequired: true,
      healthInsuranceCoverageAmountLocal: 5000,
      healthInsuranceCoverageAmountUsd: 1000,
      healthInsuranceReport: "DS40",
      transportTicketRequired: true,
      transportReturnTicketRequired: true,
      accomodationProofRequired: true,
      invitationLetterRequired: true,
      criminalReportRequired: true,
      legalGuardianConsentRequired: true,
    },
    {
      countryId: 12,
      visaId: 3,
      id: 2,
      applicationFormName: "DS40",
      applicationFormCode: "DS40",
      applicationFormUrl: "DS40",
      appointmentConfirmationRequired: true,
      documentType: "DS40",
      documentValidity: "DS40",
      documentPhotocopyQuantity: "DS40",
      eligibilityAge: "DS40",
      eligibilityAgeRange: "DS40",
      eligibilityOccupation: "DS40",
      eligibilityFamilyMember: "DS40",
      feeLocalCurrency: "DS40",
      feeLocal: 500,
      feeUsd: 100,
      photoType: "DS40",
      photoSizeMm: "DS40",
      photoSizeIn: "DS40",
      photoBackgroundColor: "DS40",
      photoQuantity: 4,
      bankStatementRequired: true,
      bankStatementAmountLocal: 5000,
      bankStatementAmountUsd: 1000,
      bankStatementAmountMonths: 3,
      employmentProofRequired: true,
      healthInsuranceRequired: true,
      healthInsuranceCoverageAmountLocal: 5000,
      healthInsuranceCoverageAmountUsd: 1000,
      healthInsuranceReport: "DS40",
      transportTicketRequired: true,
      transportReturnTicketRequired: true,
      accomodationProofRequired: true,
      invitationLetterRequired: true,
      criminalReportRequired: true,
      legalGuardianConsentRequired: true,
    },
    {
      countryId: 12,
      visaId: 4,
      id: 4,
      applicationFormName: "DS40",
      applicationFormCode: "DS40",
      applicationFormUrl: "DS40",
      appointmentConfirmationRequired: true,
      documentType: "DS40",
      documentValidity: "DS40",
      documentPhotocopyQuantity: "DS40",
      eligibilityAge: "DS40",
      eligibilityAgeRange: "DS40",
      eligibilityOccupation: "DS40",
      eligibilityFamilyMember: "DS40",
      feeLocalCurrency: "DS40",
      feeLocal: 500,
      feeUsd: 100,
      photoType: "DS40",
      photoSizeMm: "DS40",
      photoSizeIn: "DS40",
      photoBackgroundColor: "DS40",
      photoQuantity: 4,
      bankStatementRequired: true,
      bankStatementAmountLocal: 5000,
      bankStatementAmountUsd: 1000,
      bankStatementAmountMonths: 3,
      employmentProofRequired: true,
      healthInsuranceRequired: true,
      healthInsuranceCoverageAmountLocal: 5000,
      healthInsuranceCoverageAmountUsd: 1000,
      healthInsuranceReport: "DS40",
      transportTicketRequired: true,
      transportReturnTicketRequired: true,
      accomodationProofRequired: true,
      invitationLetterRequired: true,
      criminalReportRequired: true,
      legalGuardianConsentRequired: true,
    },
  ]);

  await db.insert(Images).values([
    {
      countryId: 9,
      flag: "/flag1",
      icon: "https://cdn.countryflags.com/thumbs/Argentina/flag-400.png",
    },
    {
      countryId: 12,
      flag: "/flag2",
      icon: "https://www.countryflags.com/wp-content/uploads/australia-flag-png-xl.png",
    },
  ]);
}
